/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cars;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Greg Mathews
 */
public class CarUI extends javax.swing.JFrame {

    /**
     * Creates new form CarUI
     */
    public CarUI() {
        initComponents();
    }
    public JComboBox getComboBox1(){
        return jComboBox1;
    }
    public JComboBox getComboBox2(){
        return jComboBox2;
    }
    public JComboBox getComboBox3(){
        return jComboBox3;
    }
    public JTextArea getTextArea(){
        return jTextArea1;
    }
    public String selectedMake(String selectedMake){
        //Methods in below comments are named incorrectly
//String selectedMake = getComboBoxText();
//String threeLetterMake = null;
String threeLetterMake = "";
if (selectedMake.equals("AMERICAN MOTORS OR AMC"))
	threeLetterMake = "AMC";
else if (selectedMake.equals("AUDI"))
	threeLetterMake="AUD";
else if (selectedMake.equals("BMW"))
	threeLetterMake="BMW";
else if (selectedMake.equals("BUICK"))
	threeLetterMake="BUK";
else if (selectedMake.equals("CADILLAC"))
	threeLetterMake="CAD";
else if (selectedMake.equals("CHEVROLET"))
	threeLetterMake="CHE";
else if (selectedMake.equals("CHRYSLER"))
	threeLetterMake="CRY";
else if (selectedMake.equals("DODGE"))
	threeLetterMake="DOD";
else if (selectedMake.equals("DODGE/PLYMOUTH LITE TRK & VAN"))
	threeLetterMake="DOT";
else if (selectedMake.equals("FORD LIGHT TRUCK AND VAN"))
	threeLetterMake="FDT";
else if (selectedMake.equals("FORD MEDIUM AND HEAVY TRUCK"))
	threeLetterMake="FDM";
else if (selectedMake.equals("FIAT"))
	threeLetterMake="FIA";
else if (selectedMake.equals("FORD"))
	threeLetterMake="FOR";
else if (selectedMake.equals("CHEVROLET & GMC TRUCK & VAN"))
	threeLetterMake="GMC";
else if (selectedMake.equals("HONDA"))
	threeLetterMake="HON";
else if (selectedMake.equals("INTERNATIONAL TRUCK (I.H.C.)"))
	threeLetterMake="INT";
else if (selectedMake.equals("ISUZU"))
	threeLetterMake="ISU";
else if (selectedMake.equals("LINCOLN"))
	threeLetterMake="LIN";
else if (selectedMake.equals("MERCEDES"))
	threeLetterMake="MCS";
else if (selectedMake.equals("MITSUBISHI"))
	threeLetterMake="MIT";
else if (selectedMake.equals("MERCURY"))
	threeLetterMake="MRY";
else if (selectedMake.equals("MAZDA"))
	threeLetterMake="MZD";
else if (selectedMake.equals("NISSAN/DATSUN"))
	threeLetterMake="NIS";
else if (selectedMake.equals("OLDSMOBILE"))
	threeLetterMake="OLD";
else if (selectedMake.equals("PLYMOUTH"))
	threeLetterMake="PLY";
else if (selectedMake.equals("PORSCHE"))
	threeLetterMake="POR";
else if (selectedMake.equals("PONTIAC"))
	threeLetterMake="PON";
else if (selectedMake.equals("RENAULT"))
	threeLetterMake="REN";
else if (selectedMake.equals("SAAB"))
	threeLetterMake="SAB";
else if (selectedMake.equals("SUBARU"))
	threeLetterMake="SUB";
else if (selectedMake.equals("TOYOTA"))
	threeLetterMake="TOY";
else if (selectedMake.equals("UPS"))
	threeLetterMake="UPS";
else if (selectedMake.equals("VOLKSWAGEN"))
	threeLetterMake="VOL";
else if (selectedMake.equals("HYUNDAI"))
	threeLetterMake="HUN";
else if (selectedMake.equals("YUGO"))
	threeLetterMake="YUG";
else if (selectedMake.equals("GMC TRUCK AND VAN"))
	threeLetterMake="GMM";
else
	//failure case
	;
        return threeLetterMake;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Make");

        jLabel2.setText("Model");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Year");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarUI().setVisible(true);
            }
        });
        
        
    }
    
    public class jComboBox1 implements ActionListener{
        public void actionPerformed(ActionEvent e){
            JComboBox cb = (JComboBox)e.getSource();
            String makeName = (String)cb.getSelectedItem();
            System.out.println("pressed");
            jComboBox2.addItem("test2".toString());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
